### ISSUE TITLE
Support for time units of "months since..."

### ISSUE THREAD

**Issue by pochedls** [tomvothecoder/xcdat#77]
### Is your feature request related to a problem? If yes, Please describe

One feature of CDAT is its ability to flexibly read in a large number of time units. In testing some code, I realize that xarray does not natively support "months since ..."

```
import xarray as xr

fn = 'rss_4.0_ttt_197901-202012.nc'
ds = xr.open_dataset(fn)
```

> ValueError: unable to decode time units 'months since 1979-01-01' with "calendar 'standard'". Try opening your dataset with decode_times=False or installing cftime if it is not installed.

### Describe your proposed solution
Ideally, we would be able to open and decode files like this, perhaps with other packages (e.g., [nctime](http://prodiguer.github.io/nctime/index.html)). Could a fix for this issue (and potentially other fixes) be included in xcdat utilities (e.g., [open_datasets](https://github.com/tomvothecoder/xcdat/blob/main/xcdat/utils.py#L16))? 

### Describe alternatives solutions you've considered
One obvious alternative is to force the user to use the `decode_times=False` option and deal with the time axis on their own or deal with the axis information after loading the dataset. 

### Additional context
If we had a utility to help load data, we could also add axis information (e.g., bounds) when opening the dataset and include the option of stripping out extraneous variables, e.g., `tas = xcdat.open_dataset(fn, variable='tas')`.

Additional tasks based on 7/21 meeting
- [x] Take into account dataset's calendar when decoding time

**Comment by pochedls** [comment]
In thinking about my idea under "Additional context," I realize this won't really work, because even if you drop the extra variables `tas` will still behave as a dataset, not a dataarray. It still may be useful to have a wrapper that performs basic operations when loading a dataset.

**Comment by tomvothecoder** [comment]
> @tomvothecoder - an issue that arose that inspired this ticket was that xarray does not read a pretty common time unit "months since." I'm wondering if open_dataset could be used to deal with issues like this (though perhaps not in the initial release)?
https://github.com/tomvothecoder/xcdat/issues/80#issuecomment-875136456

`xarray` uses the `cftime` module, which only supports CF convention units (no months or years). [More info here.](https://stackoverflow.com/a/64777252)

We can add the `decode_times=False` flag to `open_dataset()`, and implement a function that creates a custom time coordinate to handle `months since <date>`/`years since <date>`.
```
# Source: https://stackoverflow.com/a/55686749
import pandas as pd
import xarray as xr

ds = xr.open_dataset("C:/Users/vsri/Downloads/prcp_monthly_1948-2008.nc",
        decode_times=False)
units, reference_date = ds.time.attrs['units'].split('since')
ds['time'] = pd.date_range(start=reference_date, periods=ds.sizes['time'], freq='MS')

ds.time
<xarray.DataArray 'time' (time: 4)>
array(['2000-01-01T00:00:00.000000000', '2000-02-01T00:00:00.000000000',
       '2000-03-01T00:00:00.000000000', '2000-04-01T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-02-01 2000-03-01 2000-04-01
```

Other approaches using `decode_times=False`:
- [https://stackoverflow.com/a/47364993](https://stackoverflow.com/a/47364993)
- [https://rabernat.github.io/research_computing_2018/xarray-tips-and-tricks.html#Fix-poorly-encoded-time-coordinates](https://rabernat.github.io/research_computing_2018/xarray-tips-and-tricks.html#Fix-poorly-encoded-time-coordinates)

**Comment by tomvothecoder** [comment]
Additional tasks based on 7/21 meeting
- [ ] Take into account dataset's calendar when generating time encoding
